# Generated by Django 2.0.6 on 2018-06-13 10:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movielist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='pictures/')),
                ('date', models.DateField()),
                ('upload_date', models.DateTimeField(default=datetime.datetime(2018, 6, 13, 10, 38, 9, 666749, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('song_location', models.FileField(upload_to='')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musico.movielist')),
            ],
        ),
    ]
