# Generated by Django 2.0.6 on 2018-06-14 04:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('musico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 14, 4, 46, 25, 968527, tzinfo=utc)),
        ),
    ]
